CREATE TABLE IF NOT EXISTS temperatures (
    id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    value       DECIMAL(5,2) NOT NULL,
    recorded_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS humidities (
    id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    value       DECIMAL(5,2) NOT NULL,
    recorded_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS co2s (
    id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    value       DECIMAL(7,2) NOT NULL,
    recorded_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
